name: ChivalCore
version: '${project.version}'
main: au.chival.core.Main
api-version: 1.8.8
commands:
  sudo:
    description: /sudo
    aliases: /s
  lobby:
    description: /lobby
    aliases: [hub, l, zoo]
  vanish:
    description: /vanish
    aliases: v
  speed:
    description: /speed
    usage: /speed <speed 1 - 10>
  fly:
    description: /fly <player>
    aliases: f
  flys:
    description: /fly <player>
    aliases: fs
  rank:
    description: /rank <player> <rank>
    usage: /rank <player> <rank>
    aliases: ranks
  wtp:
    description: /wtp <world> <player>
    usage:  /wtp <world> <player>
  wc:
    description: /wc <world>
    usage: /wc <world>
  menu:
    description: /menu
    usage: /menu
  test:
    description: test stuff
    usage: /test <stuff>
  heal:
    description: test stuff
    usage: /test <stuff>
permissions:
  chival.vanish:
    description: Allows use of Vanish
  chival.fly:
    description: Allow use of Flight
  chival.wtp:
    description: Allow changing of worlds
  chival.ranks:
      description: Allow changing peoples ranks
  chival.speed:
    description: Allow changing of speed