name: ChivalCore
version: '${project.version}'
main: au.chival.core.main
api-version: 1.8.8
commands:
  fly:
    description: /fly <player>
    usage: /fly <fly>
    aliases: f
  rank:
    description: /rank <player> <rank>
    usage: /rank <player> <rank>
  wtp:
    description: /wtp <world> <player>
    usage:  /wtp <world> <player>
  wc:
    description: /wc <world>
    usage: /wc <world>
  speed:
    description: /speed <float>
    usage: /speed <float>
  menu:
    description: /menu
    usage: /menu
  test:
    description: test stuff
    usage: /test <stuff>
permissions:
  chival.fly:
    description: Allow use of Flight
  chival.wtp:
    description: Allow changing of worlds
  chival.ranks:
      description: Allow changing peoples ranks